# Utiliser une image JDK légère
FROM openjdk:17-oracle

# Spécifier l'emplacement du fichier JAR
ARG JAR_FILE=target/user-0.0.1-SNAPSHOT.jar

# Copier le fichier JAR dans le conteneur
COPY ${JAR_FILE} app.jar

# Commande pour exécuter l'application
ENTRYPOINT ["java", "-jar", "app.jar"]
